---
title: "R Notebook"
output: html_notebook
editor_options:
  chunk_output_type: console
---

```{r}
#library("RprobitB")
```

## Data preparation

```{r data}
data("choice_berserk")
choice_berserk$color <- ifelse(choice_berserk$color == "white", 1, 0)
choice_berserk$streak <- ifelse(choice_berserk$streak, 1, 0)
data <- prepare_data(
  form = berserk ~ 0 | color + rating + rating_diff + min_rem + streak,
  choice_data = choice_berserk,
  id = "player_id",
  idc = "game_id",
  standardize = c("rating","rating_diff","min_rem")
)
```

```{r plot-data}
plot(data, by_choice = TRUE)
```

## Fixed effect model

```{r mod_fix}
mod_fix <- mcmc(data)
coef(mod_fix)
```

## Random effect model

```{r mod_re}
mod_re <- nested_model(mod_fix, 
                       re = c("color","rating","rating_diff","min_rem","streak"))
coef(mod_re)
round(cov_mix(mod_re, cor = TRUE),2)
```

## Cluster model

```{r mod_cl}
mod_cl <- nested_model(mod_re, 
                       latent_classes = list("C" = 2))
coef(mod_cl)
cov_mix(mod_cl, cor = TRUE)
```
