---
title: "Applications"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Applications}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: ref.bib
link-citations: yes
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "",
  fig.align = "center",
  fig.dim = c(8, 6), 
  out.width = "75%"
)
library(RprobitB)
```

This vignette^[This vignette is built using R `r paste(R.Version()[6:7], collapse = ".")` with the {RprobitB} `r utils::packageVersion("RprobitB")` package.] presents four applications with the {RprobitB} package.

## Chess opening choice

```{r, echo = FALSE}
model_chess_opening <- readRDS("P:/RprobitB/applications/chess_opening_choice/model_chess_opening.rds")
model_chess_opening_sparse <- readRDS("P:/RprobitB/applications/chess_opening_choice/model_chess_opening_sparse.rds")
```

```{r, eval = FALSE}
choice_chess_opening <- create_lagged_cov(
  choice_data = RprobitB::choice_chess_opening,
  column = "w1",
  k = 1,
  id = "fideid_w")
```

```{r, eval = FALSE}
choice_chess_opening <- fastDummies::dummy_cols(choice_chess_opening, "w1.1")
choice_chess_opening$rating_diff <- choice_chess_opening$rating_w - choice_chess_opening$rating_b
```

```{r, eval = FALSE}
data <- prepare_data(
  form = w1 ~ w1.1 | sex_w + byear_w + rating_w + rating_diff + 1,
  choice_data = choice_chess_opening,
  id = "fideid_w",
  idc = "fideid_b",
  alternatives = c("e4","d4","b3"),
  standardize = c("byear_w","rating_w","rating_diff"),
  impute = "complete_cases"
)
```

```{r, eval = FALSE}
model_chess_opening <- mcmc(data)
```

```{r, eval = FALSE}
model_chess_opening_sparse <- nested_model(model_chess_opening,
                                           form = w1 ~ w1.1 | 1)
```

```{r}
coef(model_chess_opening)
```

```{r}
coef(model_chess_opening_sparse)
```

```{r}
model_selection(model_chess_opening_sparse, model_chess_opening,
                criteria = c("npar","LL","AIC","BIC"))
```

## Berserking choice in online chess

```{r, echo = FALSE}
model_berserk <- readRDS("P:/RprobitB/applications/berserk_choice/model_berserk.rds")
```

```{r, eval = FALSE}
choice_berserk <- create_lagged_cov(
  choice_data = RprobitB::choice_berserk,
  column = c("berserk","lost"),
  k = 1,
  id = "player_id"
)
```

```{r, eval = FALSE}
data <- prepare_data(
  form = berserk ~ 0 | white + rating + rating_diff + min_rem + streak + berserk.1 + lost.1 + 1,
  re = c("rating","min_rem","lost.1"),
  choice_data = choice_berserk,
  id = "player_id",
  idc = "game_id",
  standardize = c("rating","rating_diff","min_rem"),
  impute = "zero_out"
)
plot(data, by_choice = TRUE)
```

```{r, echo = FALSE}
plot(model_berserk$data, by_choice = TRUE)
```

```{r, eval = FALSE}
model_berserk <- mcmc(data)
```

```{r}
coef(model_berserk)
```

## Child wish

```{r, echo = FALSE}
model_child_wish <- readRDS("P:/RprobitB/applications/contraception_choice/model_child_wish.rds")
```

```{r, eval = FALSE}
data_cw <- prepare_data(
  form = child_wish ~ 0 | finance + plans + care + empl + leisure + empl_partner + household + ready,
  re = c("finance", "plans", "care", "empl", "leisure", "empl_partner", "household", "ready"),
  choice_data = contraception_data,
  id = "id",
  idc = "wave",
  impute = "complete_cases"
)
plot(data_cw, by_choice = TRUE)
```

```{r, echo = FALSE}
plot(model_child_wish$data, by_choice = TRUE)
```

```{r, eval = FALSE}
model_child_wish <- mcmc(data = data_cw,
                         prior = list("delta" = 0.1),
                         latent_classes = list("C" = 5, "dp_update" = TRUE))
```

```{r}
coef(model_child_wish)
```

## Contraception choice

```{r, eval = FALSE}
contraception_data <- subset(contraception_data,
                             subset = gender==1 & infert==0 & sex_freq>0,
                             select = c("id", "wave", "contr_method", "age", "sex_freq", "rel_stat", "child_wish"))
```

```{r, eval = FALSE}
data_cc <- prepare_data(
  form = contr_method ~ 0 | age + sex_freq + rel_stat + child_wish,
  alternatives = c("0", "1", "2", "4", "1|2"),
  re = c("age", "sex_freq", "rel_stat", "child_wish"),
  standardize = "age",
  choice_data = contraception_data,
  id = "id",
  idc = "wave",
  impute = "complete_cases"
)
```

```{r, eval = FALSE}
plot(data_cc, by_choice = TRUE)
```

```{eval = FALSE}
model_contr_method <- mcmc(data = data_cc,
                           prior = list("delta" = 0.1),
                           latent_classes = list("C" = 10, "dp_update" = TRUE))
```

## References
