test_that("differencing works", {
  expect_error(delta(0, 3))
  expect_equal(delta(1, 3), structure(c(-1, -1, 1, 0, 0, 1), dim = 2:3))
  expect_equal(delta(2, 3), structure(c(1, 0, -1, -1, 0, 1), dim = 2:3))
  expect_equal(delta(3, 3), structure(c(1, 0, 0, 1, -1, -1), dim = 2:3))
  expect_error(delta(4, 3))
  J <- sample(2:10, 1)
  diff_alt <- sample.int(J, 1)
  Sigma0 <- RprobitB:::sample_cov_matrix(dim = J)
  expect_true(is_cov_matrix(Sigma0))
  Sigma_diff0 <- RprobitB:::diff_Sigma(Sigma0, diff_alt = diff_alt)
  expect_true(is_cov_matrix(Sigma_diff0))
  Sigma1 <- RprobitB:::undiff_Sigma(Sigma_diff0, diff_alt = diff_alt)
  expect_true(is_cov_matrix(Sigma1))
  Sigma_diff1 <- RprobitB:::diff_Sigma(Sigma1, diff_alt = diff_alt)
  expect_true(is_cov_matrix(Sigma_diff1))
  expect_equal(Sigma_diff0, Sigma_diff1)
})
