#' Choice prediction
#'
#' @description
#' This function predicts the discrete choice behavior
#'
#' @details
#' Predictions are made based on the maximum predicted probability for each
#' choice alternative. See the vignette on choice prediction for a demonstration
#' on how to visualize the model's sensitivity and specificity by means of a
#' receiver operating characteristic (ROC) curve.
#'
#' @param object
#' An object of class \code{RprobitB_fit}.
#' @param data
#' Either
#' \itemize{
#'   \item \code{NULL}, using the data in \code{object},
#'   \item an object of class \code{RprobitB_data}, for example the test part
#'         generated by \code{\link{train_test}},
#'   \item or a data frame of custom choice characteristics. It must have the
#'         same structure as `choice_data` used in \code{\link{prepare_data}}.
#'         Missing columns or \code{NA} values are set to 0.
#' }
#' @param overview
#' If \code{TRUE}, returns a confusion matrix.
#' @param ...
#' Ignored.
#'
#' @return
#' Either a table if \code{overview = TRUE} or a data frame otherwise.
#'
#' @examples
#' data <- simulate_choices(form = choice ~ cov, N = 10, T = 10, J = 2, seed = 1)
#' data <- train_test(data, test_proportion = 0.5)
#' model <- mcmc(data$train)
#' coef(model)
#' predict(model)
#' predict(model, overview = FALSE)
#' predict(model, data = data$test)
#' predict(model, data = data.frame("cov_A" = c(1,1,NA,NA), "cov_B" = c(1,NA,1,NA)),
#'         overview = FALSE)
#' @export

predict.RprobitB_fit <- function(object, data = NULL, overview = TRUE, ...) {

  ### choose data
  if (is.null(data)) {
    data <- object$data
  } else if (is.data.frame(data)) {
    cov <- object$data$res_var_names$cov
    data_build <- matrix(0, nrow = nrow(data), ncol = 1 + length(cov))
    colnames(data_build) <- c("id", cov)
    data_build[,"id"] <- 1:nrow(data)
    for(col in colnames(data)){
      if(col %in% colnames(data_build)){
        data_build[,col] <- data[,col]
      }
    }
    data <- prepare_data(
      form = object$data$form, choice_data = as.data.frame(data_build),
      re = object$data$re, alternatives = object$data$alternatives, id = "id",
      idc = NULL, standardize = NULL, missing_data = "zero_out")
  }
  if (class(data) != "RprobitB_data") {
    stop("'data' is not of class 'RprobitB_data'.")
  }

  ### compute choice probabilites
  choice_probs <- as.data.frame(choice_probabilities(object, data = data))

  ### check if true choices are available
  if (data$choice_available) {
    true_choices <- data$choice_data[[data$res_var_names$choice]]
    true_choices <- factor(true_choices, labels = data$alternatives)
  }

  ### predict
  prediction <- data$alternatives[apply(choice_probs[data$alternatives], 1, which.max)]

  ### create and return output
  if (overview) {
    if (data$choice_available) {
      out <- table(true_choices, prediction, dnn = c("true", "predicted"))
    } else {
      out <- table(prediction, dnn = c("prediction"))
    }
  } else {
    if (data$choice_available) {
      out <- cbind(choice_probs,
        "true" = true_choices, "predicted" = prediction,
        "correct" = (true_choices == prediction)
      )
    } else {
      out <- cbind(choice_probs, "prediction" = prediction)
    }
  }
  return(out)
}
