#' Transform fitted \code{RprobitB_model}
#' @description
#' For an \code{RprobitB_model}, this function can:
#' \itemize{
#'   \item change the length \code{B} of the burn-in period,
#'   \item change the thinning factor \code{Q},
#'   \item change the utility normalization \code{scale}.
#' }
#' @details
#' For more details see the vignette "Model fitting":
#' \code{vignette("model_fitting", package = "RprobitB")} or "Model checking and
#' model selection":
#' \code{vignette("model_checking_and_model_selection", package = "RprobitB")}
#' @inheritParams fit
#' @param model
#' An object of class \code{RprobitB_model}. Such an object is generated by the
#' function \code{\link{fit}}.
#' @return
#' An object of class \code{RprobitB_model}.
#' @examples
#' ### fit a model to simulated data
#' data = simulate(form = choice ~ var | 1, N = 100, T = 10, J = 2)
#' scale = list("parameter" = "s", "index" = 1, "value" = 1)
#' model = fit(data = data, R = 1e4, B = 1, Q = 1)
#'
#' ### change 'B' and 'Q'
#' model = transform(model = model, B = 1e4/2, Q = 10)
#'
#' ### change 'scale'
#' scale = list("parameter" = "a", "index" = 1, "value" = -1)
#' model = transform(model = model, scale = scale)
#' @export

transform = function(model, B = NULL, Q = NULL, scale = NULL) {

  ### check inputs
  if(!inherits(model,"RprobitB_model"))
    stop("'model' must be of class 'RprobitB_model'.")
  B = if(is.null(B)) model$B else B
  Q = if(is.null(Q)) model$Q else Q
  R = model$R
  P_f = model$RprobitB_data$P_f
  J = model$RprobitB_data$J
  if(!is.numeric(B) || !B%%1 == 0 || !B>0 || !B<R)
    stop("'B' must be a positive integer smaller than 'R'.")
  if(!is.numeric(Q) || !Q%%1 == 0 || !Q>0 || !Q<R)
    stop("'Q' must be a positive integer smaller than 'R'.")
  scale = if(is.null(scale))
    model$scale else check_scale(scale = scale, P_f = P_f, J = J)

  ### normalize, burn and thin Gibbs samples
  gibbs_samples = transform_gibbs_samples(
    gibbs_samples = model$gibbs_samples$gibbs_samples, R = R, B = B, Q = Q,
    scale = scale)

  ### compute statistics from Gibbs samples
  statistics = compute_parameter_statistics(
    gibbs_samples = gibbs_samples, P_f = model$RprobitB_data$P_f,
    P_r = model$RprobitB_data$P_r, J = model$RprobitB_data$J,
    C = model$latent_classes$C)

  ### scale true parameters
  if(model$RprobitB_data$simulated)
    parm = transform_parm(parm = model$RprobitB_data$parm, scale = scale)

  ### rebuild and return 'RprobitB_model'
  model$B = B
  model$Q = Q
  model$scale = scale
  model$gibbs_samples = gibbs_samples
  model$statistics = statistics
  model$RprobitB_data$parm = parm
  return(model)

}
