#' Transform fitted \code{RprobitB_model}
#' @description
#' Function that transforms a fitted \code{RprobitB_model} in three ways:
#' \itemize{
#'   \item Change the length \code{B} of the burn-in period
#'   \item Change the thinning factor \code{Q}
#'   \item Change the utility normalization \code{scale}
#' }
#' @details
#' For more details see the vignette "Model fitting":
#' \code{vignette("model_fitting", package = "RprobitB")}
#' @inheritParams fit
#' @param RprobitB_model
#' An object of class \code{RprobitB_model}. Such an object is generated by the
#' function \code{\link{fit}}.
#' @return
#' An object of class \code{RprobitB_model}.
#' @export

transform = function(RprobitB_model, B = NULL, Q = NULL, scale = NULL) {

  ### extract parameters
  B = if(is.null(B)) RprobitB_model$B else B
  Q = if(is.null(Q)) RprobitB_model$Q else Q
  scale = if(is.null(scale)) RprobitB_model$scale else scale
  gibbs_samples = RprobitB_model$gibbs_samples$gibbs_samples
  parm = RprobitB_model$RprobitB_data$parm

  ### normalize, burn and thin Gibbs samples
  gibbs_samples = transform_gibbs_samples(
    gibbs_samples = gibbs_samples, R = RprobitB_model$R, B = B, Q = Q,
    scale = scale)

  ### compute statistics from Gibbs samples
  statistics = compute_statistics(
    gibbs_samples = gibbs_samples, P_f = RprobitB_model$RprobitB_data$P_f,
    P_r = RprobitB_model$RprobitB_data$P_r, J = RprobitB_model$RprobitB_data$J,
    C = RprobitB_model$latent_classes$C)

  ### scale true parameters
  parm = transform_parm(parm = parm, scale = scale)

  ### rebuild and return 'RprobitB_model'
  RprobitB_model$B = B
  RprobitB_model$Q = Q
  RprobitB_model$scale = scale
  RprobitB_model$gibbs_samples = gibbs_samples
  RprobitB_model$RprobitB_data$parm = parm
  return(RprobitB_model)

}
